### ISSUE TITLE
Cannot Set Input Initially Empty

### ISSUE THREAD

**Issue by inaki-ibarra** [josemarluedke/ember-cli-daterangepicker#23]
"If you're using a date range as a filter, you may want to leave it empty by default."

See example here:
http://www.daterangepicker.com/#ex5

**Comment by inakiibarra** [comment]
Or maybe at least set a Default text?

**Comment by planetexpress69** [comment]
+1

**Comment by gregjopa** [comment]
You can use the `autoUpdateInput` parameter to make the input empty by default. Try this code: 
```handlebars
{{date-range-picker
  autoUpdateInput=false
}}
```

Let me know if this resolves your issue.

**Comment by WillEngler** [comment]
I am using this addon for an empty-by-default datepicker and can confirm that `autoUpdateInput=false` did the trick. Thanks!

**Comment by sskarabej** [comment]
I'm using  v0.6.0
Set `autoUpdateInput`=false. Inputbox is initially empty.
Open the (empty) picker and close it by clicking anywhere on the page. BS Daterangepicker will trigger `outsideClick.daterangepicker` event. But also, before that, it will trigger `hide.daterangepicker` before.

In `handleDateRangePickerEvent` handler, addon will set properties for `start` and `end` based on BS picker's startDate and endDate. These are by deafault today's date even though I haven't defined them.  Because `rangeText` is computed property based od `start` and `end` values, inputbox will end up being populated with this date range. Addon should leave the inputbox empty untill user intentionally sets the range.

For comparison, with empty inputbox on start - click Cancel button and it will perform as desired. But click anywhere outside the date-range-picker will populate the inputbox.

**Comment by yusufsagdic** [comment]
@carrotalan I have same issue.
