### ISSUE TITLE
Separator option does not work

### ISSUE THREAD

**Issue by veegandhi** [josemarluedke/ember-cli-daterangepicker#54]
I think separator option should lie under locale object. Thanks for fantastic work.

**Comment by josemarluedke** [comment]
Could you create a reproduction of this problem using ember-twiddle.com ?

**Comment by monovertex** [comment]
Not the original submitter, but me and a co-worker also hit this problem. A twiddle doesn't seem to be possible, because there's an incompatibility between it and `ember-cli-moment-shim` ([see this issue](https://github.com/jasonmit/ember-cli-moment-shim/issues/98)). We created a new app locally and tested it.

By looking at the source code of `ember-cli-daterangepicker`, I don't think that the `rangeText` computed property is used anywhere, or at least I can't find where it is used. So the `separator` property is not used at all by `ember-cli-daterangepicker`.

From what I understand, the `separator` option is passed directly to `bootstrap-daterangepicker`, but the documentation does not describe this option. However, this option *is* described in the `locale` property.

See here an example using their configuration generator:

```
$('#demo').daterangepicker({
    "locale": {
        "format": "MM/DD/YYYY",
        "separator": " - ",
        "applyLabel": "Apply",
        "cancelLabel": "Cancel",
        "fromLabel": "From",
        "toLabel": "To",
        "customRangeLabel": "Custom",
        "weekLabel": "W",
        "daysOfWeek": [
            "Su",
            "Mo",
            "Tu",
            "We",
            "Th",
            "Fr",
            "Sa"
        ],
        "monthNames": [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
        ],
        "firstDay": 1
    },
    "startDate": "01/19/2017",
    "endDate": "01/25/2017"
});
```

The fix is simply moving the `separator` property.
