### ISSUE TITLE
sendAction issue

### ISSUE THREAD

**Issue by mrosenberg** [josemarluedke/ember-cli-daterangepicker#66]
The attrs param is sent with a spread operator which is causing it to disappear into the ether. 

https://github.com/josemarluedke/ember-cli-daterangepicker/blob/master/addon/components/date-range-picker.js#L203

I propose rewriting it without the spread which seems to work fine.

**Comment by engwan** [comment]
The problem is `attrs` is a hash because it is used in the `setProperties` call below.

For the `sendAction`, the params should be `[start, end]`.

The solution by @kumkanillam works, but you'll be getting a single hash as the parameter of the apply action instead of start and end date as separate parameters.

**Comment by kumkanillam** [comment]
`this.sendAction(actionName, attrs.start, attrs.end, picker);` - this code will pass  start-date if start-date is available if not it will pass `undefined` . Is this code change is okay @engwan

**Comment by engwan** [comment]
Yeah, that will work correctly for the `applyAction` use case.

For the `cancelAction` case, it will call: `cancelAction(undefined, undefined, picker)` which might be weird.
